name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use nightly rust
      run: rustup default nightly
    - name: Use nightly rust toolchain
      run: rustup toolchain install nightly --component rust-src
    - name: Add target
      run: rustup target add riscv32imc-unknown-none-elf
    - name: Build
      run: cargo build --verbose
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Check formatting
      run: cargo fmt --check
    # - name: Run tests
    #   run: cargo test --verbose
